### ISSUE TITLE
NullPointerException on Second Load

### ISSUE THREAD

**Issue by pzich** [Bukkit/SamplePlugin#5]
I believe there's an issue with Bukkit unregistering and reregistering commands. If a server is started up with a plugin in place that uses getCommand("..."), and that plugin is disabled with /plugin disable PluginName, when it is loaded again with /plugin load PluginName it returns a null pointer. I thought there was an issue with how I wrote my onEnable and onDisable but it seems this plugin suffers from it as well.

**Comment by kne1p** [comment]
This seems to be a problem of Bukkit or CraftBukkit, and not the SamplePlugin itself, the issue should be reported here
https://github.com/Bukkit/Bukkit
or here
https://github.com/Bukkit/CraftBukkit
