### ISSUE TITLE
Out of date function reference?

### ISSUE THREAD

**Issue by highb** [Bukkit/SamplePlugin#9]
https://github.com/Bukkit/SamplePlugin/blob/master/src/main/java/com/dinnerbone/bukkit/sample/SamplePosCommand.java
Line 39: teleportTo seems to be an invalid function name. Does this need to be changed to teleport?

**Comment by kne1p** [comment]
This is fixed by the pull request issued by Pandarr, or alternatively by my pull request.

A patched fork of SamplePlugin is available at
https://github.com/kne1p/SamplePlugin

**Comment by feildmaster** [comment]
I lied in the PR.. but this has been fixed.
